### ISSUE TITLE
Plugin does not work

### ISSUE THREAD

**Issue by nlotambov** [OllisGit/Octoprint-AutostartPrint#2]
Hi, my plugin does not work at all. After turning on and loading the octoprint, the plugin does not start printing. The plugin is activated, auto-connect is working.

**Comment by OllisGit** [comment]
Hi @nlotambov,
do you have a sub-folder in your upload folder? I think thats could be the problem?
Please attach the octoprint.log to this issue, so that I can verify my assumption.

**Comment by OllisGit** [comment]
Hi @nlotambov,
the issue with the sub-folder is fixed in the new version 1.1.2.

Please test and give a feedback
Thx,
Olli

**Comment by nlotambov** [comment]
Hi @OllisGit,
Yes, I have subfolders, but the new file was at the root. I’ll try to check today.

**Comment by nlotambov** [comment]
@OllisGit, can I somehow improve the plugin?
1. Force to start the plugin, pressing a button. For example, I already have the printer turned on and I want to start the timer.
2. The timer is not only seconds, but also minutes and hours.
3. Select any file.

**Comment by OllisGit** [comment]
Hi @nlotambov!

1)  hmm...it's possible to implement, but where should I place the button? In NavBar? Next to the checkbox? As a workaround you can use the "disconnect", "connect" button. Instead of one, you need to press this button twice
2) well just do some math: hour * 60  * 60 or minute * 60 ;-)  
3) jap, this was on my todo list as well, but currently my main focus are my new plugins: "PrintJobHistory" and "SpoolManager", so I think I don't have time for this feature the next month. But I will create an issue for that feature request.

**Comment by nlotambov** [comment]
Hi @OllisGit, the plugin has started.  But it only works with files in the root directory.
But files in subdirectories do not work.
The button can be placed anywhere.  The main thing that would be convenient.  If I want to postpone printing for several hours, what is the maximum value in seconds?

**Comment by OllisGit** [comment]
Hi @nlotambov! 
- I created a new issue for supporting sub-folders (#5).
- I am not sure about the button, if it's realy needed....will check and come back later
- Use the max integer java-script value: 9007199254740991 seconds

**Comment by OllisGit** [comment]
Hi @nlotambov,
the sub folder feature is now implemented in V1.3.0. Could be activate in Plugin-Settings.

Please test and give feedback.

PS. sorry for the delay, but I was busy with my other new plugins : PrintJobHistory and SpoolManager.

**Comment by OllisGit** [comment]
No feedback!
